### PR TITLE
Got war working

### PR DESCRIPTION
**Pull request by AlphaMorgothist**
War works now

### CODE REVIEW

**Review by MikeSweeny — APPROVED** [review]
Looks Good Dood!

**Comment by MikeSweeny** [comment]
MERGE THIS SHIT YO

**Comment by StevenCoverdale** [comment]
Need to fix your conflicts first
image

**Comment by AlphaMorgothist** [comment]
Is this from school?

Sent from my Bell Samsung device over Canada’s largest network.
________________________________

**Comment by MikeSweeny** [comment]
@AlphaMorgothist lol I think so, I didnt look closely and thought it was TT. Just cleaning up my github since im actually using it lately and havent checked this page in ages. Also a bait to get you to look at github and maybe work on TT.

**Comment by AlphaMorgothist** [comment]
Damn it I would love nothing more I feel like I'm getting so far away from everything that I actually love doing

Sent from my Bell Samsung device over Canada’s largest network.
________________________________

**Comment by AlphaMorgothist** [comment]
Nein!

Sent from my Bell Samsung device over Canada’s largest network.
________________________________

**Comment by MikeSweeny** [comment]
Its cluttering up my gitHub views for work lol. Make a commit I dare you.

**Pull request closed without merging**
